// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAULNa3dmPgQC3a-z_TerHoIY7wmZqAtlw',
    appId: '1:64488744286:web:f1c08366f6537abfab9bcf',
    messagingSenderId: '64488744286',
    projectId: 'diabetes-care-taker',
    authDomain: 'diabetes-care-taker.firebaseapp.com',
    storageBucket: 'diabetes-care-taker.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlSg0mtKzixIbNBXPSXJNbLmYlOFieCfQ',
    appId: '1:64488744286:android:5140bf62710ea6a9ab9bcf',
    messagingSenderId: '64488744286',
    projectId: 'diabetes-care-taker',
    storageBucket: 'diabetes-care-taker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxSCCwQ8SKz4STvPhcKgqAY7M1fYYJzgE',
    appId: '1:64488744286:ios:2ec3175661c0cb22ab9bcf',
    messagingSenderId: '64488744286',
    projectId: 'diabetes-care-taker',
    storageBucket: 'diabetes-care-taker.appspot.com',
    iosBundleId: 'com.example.diabetesCareTaker',
  );
}
